[package]
name = "mybar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7.8"
chrono = "0.4.31"
sysinfo = "0.30.5"
interfaces= "0.0.9"
